[package]
name = "gpx_split"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.6"
gpx = "0.9.1"
haversine-rs = "0.3.0"

[build-dependencies]
copy_to_output = "2.1.0"
